apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  PORT: "8888"
  MYSQL_HOST: mysql
  MYSQL_DATABASE: user_database
  MYSQL_USER: sumit


---


apiVersion: v1
kind: Secret
metadata:
  name: node-secret
type: Opaque
data:
  MYSQL_PASSWORD: cGFzc2FuZHBhc3M=
